SELECT PUBLIC_HOUSING_AGENCY_NAME,
		MR_INSPECTION_DATE,
        SECOND_MR_INSPECTION_DATE,
        MR_INSPECTION_COST,
        SECOND_MR_INSPECTION_COST,
		MR_INSPECTION_COST - SECOND_MR_INSPECTION_COST AS CHANGE_IN_COST,
        ((MR_INSPECTION_COST - SECOND_MR_INSPECTION_COST)/SECOND_MR_INSPECTION_COST) * 100 AS PERCENT_CHANGE_IN_COST
FROM
(SELECT PUBLIC_HOUSING_AGENCY_NAME,
	MAX(INSPECTION_DATE) AS MR_INSPECTION_DATE, 
    LEAD_DATE AS SECOND_MR_INSPECTION_DATE,
    COST_OF_INSPECTION_IN_DOLLARS AS MR_INSPECTION_COST,
    LEAD_COST AS SECOND_MR_INSPECTION_COST    
FROM
(SELECT PUBLIC_HOUSING_AGENCY_NAME,
		COST_OF_INSPECTION_IN_DOLLARS - LEAD_COST AS DIFFERENCE,
        COST_OF_INSPECTION_IN_DOLLARS,
        INSPECTION_DATE,
        LEAD_COST,
        LEAD_DATE
FROM
(SELECT PUBLIC_HOUSING_AGENCY_NAME,
	STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y') AS INSPECTION_DATE,
    COST_OF_INSPECTION_IN_DOLLARS,
    LEAD(COST_OF_INSPECTION_IN_DOLLARS) 
    OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ) AS LEAD_COST,
    LEAD(STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y'))
    OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME) AS LEAD_DATE
FROM public_housing_inspection_data
ORDER BY PUBLIC_HOUSING_AGENCY_NAME, INSPECTION_DATE DESC
) SubQuery 

) SubQuery2
WHERE DIFFERENCE > 0
GROUP BY PUBLIC_HOUSING_AGENCY_NAME) MainQuery;



